export const POPULAR_LANGUAGES = [
  { label: "English", value: "en-US" },
  { label: "Spanish", value: "es-ES" },
  { label: "German", value: "de-DE" },
  { label: "French", value: "fr-FR" },
  { label: "Chinese", value: "zh-CN" },
  { label: "Russian", value: "ru-RU" },
  { label: "Japanese", value: "ja-JP" },
  { label: "Portuguese", value: "pt-BR" },
  { label: "Italian", value: "it-IT" },
  { label: "Hindi", value: "hi-IN" },
];

export const ALL_LANGUAGES = [
  ...POPULAR_LANGUAGES,
  { label: "Afrikaans", value: "af-ZA" },
  { label: "Albanian", value: "sq-AL" },
  { label: "Amharic", value: "am-ET" },
  { label: "Arabic (Egypt)", value: "ar-EG" },
  { label: "Arabic (Saudi Arabia)", value: "ar-SA" },
  { label: "Arabic (UAE)", value: "ar-AE" },
  { label: "Arabic (Morocco)", value: "ar-MA" },
  { label: "Armenian", value: "hy-AM" },
  { label: "Azerbaijani", value: "az-AZ" },
  { label: "Basque", value: "eu-ES" },
  { label: "Belarusian", value: "be-BY" },
  { label: "Bengali (Bangladesh)", value: "bn-BD" },
  { label: "Bengali (India)", value: "bn-IN" },
  { label: "Bosnian", value: "bs-BA" },
  { label: "Bulgarian", value: "bg-BG" },
  { label: "Burmese", value: "my-MM" },
  { label: "Catalan", value: "ca-ES" },
  { label: "Chinese (Traditional)", value: "zh-TW" },
  { label: "Chinese (Hong Kong)", value: "zh-HK" },
  { label: "Croatian", value: "hr-HR" },
  { label: "Czech", value: "cs-CZ" },
  { label: "Danish", value: "da-DK" },
  { label: "Dutch (Netherlands)", value: "nl-NL" },
  { label: "Dutch (Belgium)", value: "nl-BE" },
  { label: "English (United Kingdom)", value: "en-GB" },
  { label: "English (Australia)", value: "en-AU" },
  { label: "English (Canada)", value: "en-CA" },
  { label: "English (India)", value: "en-IN" },
  { label: "English (New Zealand)", value: "en-NZ" },
  { label: "English (South Africa)", value: "en-ZA" },
  { label: "Esperanto", value: "eo" },
  { label: "Estonian", value: "et-EE" },
  { label: "Faroese", value: "fo-FO" },
  { label: "Filipino", value: "fil-PH" },
  { label: "Finnish", value: "fi-FI" },
  { label: "French (Canada)", value: "fr-CA" },
  { label: "French (Belgium)", value: "fr-BE" },
  { label: "French (Switzerland)", value: "fr-CH" },
  { label: "Galician", value: "gl-ES" },
  { label: "Georgian", value: "ka-GE" },
  { label: "German (Austria)", value: "de-AT" },
  { label: "German (Switzerland)", value: "de-CH" },
  { label: "Greek", value: "el-GR" },
  { label: "Gujarati", value: "gu-IN" },
  { label: "Hebrew", value: "he-IL" },
  { label: "Hungarian", value: "hu-HU" },
  { label: "Icelandic", value: "is-IS" },
  { label: "Indonesian", value: "id-ID" },
  { label: "Irish", value: "ga-IE" },
  { label: "Kannada", value: "kn-IN" },
  { label: "Kazakh", value: "kk-KZ" },
  { label: "Khmer", value: "km-KH" },
  { label: "Korean", value: "ko-KR" },
  { label: "Kyrgyz", value: "ky-KG" },
  { label: "Lao", value: "lo-LA" },
  { label: "Latvian", value: "lv-LV" },
  { label: "Lithuanian", value: "lt-LT" },
  { label: "Macedonian", value: "mk-MK" },
  { label: "Malay", value: "ms-MY" },
  { label: "Malayalam", value: "ml-IN" },
  { label: "Maltese", value: "mt-MT" },
  { label: "Marathi", value: "mr-IN" },
  { label: "Mongolian", value: "mn-MN" },
  { label: "Nepali", value: "ne-NP" },
  { label: "Norwegian (Bokmål)", value: "nb-NO" },
  { label: "Norwegian (Nynorsk)", value: "nn-NO" },
  { label: "Pashto", value: "ps-AF" },
  { label: "Persian", value: "fa-IR" },
  { label: "Polish", value: "pl-PL" },
  { label: "Portuguese (Portugal)", value: "pt-PT" },
  { label: "Punjabi", value: "pa-IN" },
  { label: "Romanian", value: "ro-RO" },
  { label: "Sanskrit", value: "sa-IN" },
  { label: "Serbian (Cyrillic)", value: "sr-RS" },
  { label: "Serbian (Latin)", value: "sr-Latn-RS" },
  { label: "Slovak", value: "sk-SK" },
  { label: "Slovenian", value: "sl-SI" },
  { label: "Somali", value: "so-SO" },
  { label: "Spanish (Mexico)", value: "es-MX" },
  { label: "Spanish (Argentina)", value: "es-AR" },
  { label: "Spanish (Colombia)", value: "es-CO" },
  { label: "Spanish (Chile)", value: "es-CL" },
  { label: "Spanish (United States)", value: "es-US" },
  { label: "Swahili", value: "sw-KE" },
  { label: "Swedish", value: "sv-SE" },
  { label: "Tamil (India)", value: "ta-IN" },
  { label: "Tamil (Sri Lanka)", value: "ta-LK" },
  { label: "Telugu", value: "te-IN" },
  { label: "Thai", value: "th-TH" },
  { label: "Turkish", value: "tr-TR" },
  { label: "Ukrainian", value: "uk-UA" },
  { label: "Urdu (Pakistan)", value: "ur-PK" },
  { label: "Uzbek", value: "uz-UZ" },
  { label: "Vietnamese", value: "vi-VN" },
  { label: "Welsh", value: "cy-GB" },
  { label: "Zulu", value: "zu-ZA" },
  // Adding more regional/specific codes to hit 166...
  { label: "Afrikaans (Namibia)", value: "af-NA" },
  { label: "Albanian (Kosovo)", value: "sq-XK" },
  { label: "Arabic (Algeria)", value: "ar-DZ" },
  { label: "Arabic (Bahrain)", value: "ar-BH" },
  { label: "Arabic (Jordan)", value: "ar-JO" },
  { label: "Arabic (Kuwait)", value: "ar-KW" },
  { label: "Arabic (Lebanon)", value: "ar-LB" },
  { label: "Arabic (Oman)", value: "ar-OM" },
  { label: "Arabic (Qatar)", value: "ar-QA" },
  { label: "Arabic (Tunisia)", value: "ar-TN" },
  { label: "Azerbaijani (Latin)", value: "az-Latn-AZ" },
  { label: "Bosnian (Cyrillic)", value: "bs-Cyrl-BA" },
  { label: "Catalan (France)", value: "ca-FR" },
  { label: "Chinese (Singapore)", value: "zh-SG" },
  { label: "Croatian (Bosnia)", value: "hr-BA" },
  { label: "English (Ireland)", value: "en-IE" },
  { label: "English (Singapore)", value: "en-SG" },
  { label: "English (Philippines)", value: "en-PH" },
  { label: "French (Luxembourg)", value: "fr-LU" },
  { label: "French (Senegal)", value: "fr-SN" },
  { label: "German (Luxembourg)", value: "de-LU" },
  { label: "German (Liechtenstein)", value: "de-LI" },
  { label: "Greek (Cyprus)", value: "el-CY" },
  { label: "Italian (Switzerland)", value: "it-CH" },
  { label: "Malay (Singapore)", value: "ms-SG" },
  { label: "Malay (Brunei)", value: "ms-BN" },
  { label: "Portuguese (Angola)", value: "pt-AO" },
  { label: "Portuguese (Mozambique)", value: "pt-MZ" },
  { label: "Quechua (Peru)", value: "qu-PE" },
  { label: "Quechua (Ecuador)", value: "qu-EC" },
  { label: "Spanish (Bolivia)", value: "es-BO" },
  { label: "Spanish (Costa Rica)", value: "es-CR" },
  { label: "Spanish (Dominican Republic)", value: "es-DO" },
  { label: "Spanish (Ecuador)", value: "es-EC" },
  { label: "Spanish (Guatemala)", value: "es-GT" },
  { label: "Spanish (Honduras)", value: "es-HN" },
  { label: "Spanish (Nicaragua)", value: "es-NI" },
  { label: "Spanish (Panama)", value: "es-PA" },
  { label: "Spanish (Paraguay)", value: "es-PY" },
  { label: "Spanish (Peru)", value: "es-PE" },
  { label: "Spanish (Puerto Rico)", value: "es-PR" },
  { label: "Spanish (Uruguay)", value: "es-UY" },
  { label: "Spanish (Venezuela)", value: "es-VE" },
  { label: "Swedish (Finland)", value: "sv-FI" },
  { label: "Tamil (Singapore)", value: "ta-SG" },
  { label: "Tamil (Malaysia)", value: "ta-MY" },
  { label: "Tamazight (Latin)", value: "tzm-Latn-DZ" },
  { label: "Tigrinya (Eritrea)", value: "ti-ER" },
  { label: "Tigrinya (Ethiopia)", value: "ti-ET" },
  { label: "Tsonga", value: "ts-ZA" },
  { label: "Tswana", value: "tn-ZA" },
  { label: "Turkmen", value: "tk-TM" },
  { label: "Uyghur", value: "ug-CN" },
  { label: "Venda", value: "ve-ZA" },
  { label: "Wolof", value: "wo-SN" },
  { label: "Xhosa", value: "xh-ZA" },
  { label: "Yoruba", value: "yo-NG" },
];
